# Generated by Django 4.2.17 on 2025-01-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='resources',
            new_name='resource',
        ),
    ]
