# Generated by Django 4.2.17 on 2025-01-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_resources_deployment_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='deployment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='image_name',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='creation_timestamp',
            new_name='timestamp',
        ),
    ]
