# Generated by Django 4.2.17 on 2025-01-05 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_deployment_id_deployment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_preset_containers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='create_deployments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='delete_deployments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='manage_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='manage_kubernetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dev', 'Dev'), ('researcher', 'Researcher')], default='researcher', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='view_logs',
            field=models.BooleanField(default=False),
        ),
    ]
